"""Add account_sequence to Comment

Revision ID: 0c86fc2a3e47
Revises: df7691a5aec6
Create Date: 2025-11-11 22:58:15.248557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c86fc2a3e47'
down_revision: Union[str, Sequence[str], None] = 'df7691a5aec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
