"""Add last_modified_by_id to Reference

Revision ID: 1125606e3c47
Revises: 848b5a6ff9e3
Create Date: 2025-10-23 09:52:33.959689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1125606e3c47'
down_revision: Union[str, Sequence[str], None] = '848b5a6ff9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'account_sequence',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comments', 'text')
    op.add_column('references', sa.Column('last_modified_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_references_title'), 'references', ['title'], unique=True)
    op.create_foreign_key(None, 'references', 'users', ['last_modified_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'references', type_='foreignkey')
    op.drop_index(op.f('ix_references_title'), table_name='references')
    op.drop_column('references', 'last_modified_by_id')
    op.add_column('comments', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('comments', 'account_sequence',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
