"""Add account_sequence to Comment

Revision ID: 1f9cfa12ee1b
Revises: a9502652f949
Create Date: 2025-11-06 20:45:59.415107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9cfa12ee1b'
down_revision: Union[str, Sequence[str], None] = 'a9502652f949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_product_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketing_product_id', sa.Integer(), nullable=False),
    sa.Column('keyword_text', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marketing_product_id'], ['marketing_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_product_keywords_id'), 'homepage_product_keywords', ['id'], unique=False)
    op.create_table('homepage_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('current_product_id', sa.Integer(), nullable=True),
    sa.Column('is_blog_manager', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_product_id'], ['marketing_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_homepage_workers_id'), 'homepage_workers', ['id'], unique=False)
    op.create_table('homepage_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('account_pw', sa.String(), nullable=False),
    sa.Column('blog_url', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('assigned_worker_id', sa.Integer(), nullable=True),
    sa.Column('assignment_order', sa.Integer(), nullable=True),
    sa.Column('daily_post_limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['blog_workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_homepage_accounts_id'), 'homepage_accounts', ['id'], unique=False)
    op.create_table('homepage_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(), nullable=False),
    sa.Column('post_body', sa.Text(), nullable=False),
    sa.Column('keyword_text', sa.String(), nullable=False),
    sa.Column('post_url', sa.String(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('keyword_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('marketing_product_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('blog_account_id', sa.Integer(), nullable=False),
    sa.Column('is_registration_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_account_id'], ['blog_accounts.id'], ),
    sa.ForeignKeyConstraint(['marketing_product_id'], ['marketing_products.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['blog_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_posts_id'), 'homepage_posts', ['id'], unique=False)
    op.create_table('homepage_keyword_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('marketing_product_id', sa.Integer(), nullable=False),
    sa.Column('keyword_text', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_post_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completed_post_id'], ['blog_posts.id'], ),
    sa.ForeignKeyConstraint(['marketing_product_id'], ['marketing_products.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['blog_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_keyword_progress_id'), 'homepage_keyword_progress', ['id'], unique=False)
    op.create_table('homepage_post_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=False),
    sa.Column('image_order', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_post_images_id'), 'homepage_post_images', ['id'], unique=False)
    op.create_table('homepage_post_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('blog_account_id', sa.Integer(), nullable=False),
    sa.Column('marketing_product_id', sa.Integer(), nullable=False),
    sa.Column('keyword_text', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('blog_post_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_account_id'], ['blog_accounts.id'], ),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ),
    sa.ForeignKeyConstraint(['marketing_product_id'], ['marketing_products.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['blog_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_post_schedules_id'), 'homepage_post_schedules', ['id'], unique=False)
    op.create_table('homepage_work_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('keyword_text', sa.String(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('marketing_product_id', sa.Integer(), nullable=False),
    sa.Column('blog_account_id', sa.Integer(), nullable=False),
    sa.Column('completed_post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_account_id'], ['blog_accounts.id'], ),
    sa.ForeignKeyConstraint(['completed_post_id'], ['blog_posts.id'], ),
    sa.ForeignKeyConstraint(['marketing_product_id'], ['marketing_products.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['blog_workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_work_tasks_id'), 'homepage_work_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homepage_work_tasks_id'), table_name='homepage_work_tasks')
    op.drop_table('homepage_work_tasks')
    op.drop_index(op.f('ix_homepage_post_schedules_id'), table_name='homepage_post_schedules')
    op.drop_table('homepage_post_schedules')
    op.drop_index(op.f('ix_homepage_post_images_id'), table_name='homepage_post_images')
    op.drop_table('homepage_post_images')
    op.drop_index(op.f('ix_homepage_keyword_progress_id'), table_name='homepage_keyword_progress')
    op.drop_table('homepage_keyword_progress')
    op.drop_index(op.f('ix_homepage_posts_id'), table_name='homepage_posts')
    op.drop_table('homepage_posts')
    op.drop_index(op.f('ix_homepage_accounts_id'), table_name='homepage_accounts')
    op.drop_table('homepage_accounts')
    op.drop_index(op.f('ix_homepage_workers_id'), table_name='homepage_workers')
    op.drop_table('homepage_workers')
    op.drop_index(op.f('ix_homepage_product_keywords_id'), table_name='homepage_product_keywords')
    op.drop_table('homepage_product_keywords')
    # ### end Alembic commands ###
