"""Add MarketingPost table

Revision ID: 21ce77417b5a
Revises: 3b1b3b0a433c
Create Date: 2025-10-23 12:53:49.521034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ce77417b5a'
down_revision: Union[str, Sequence[str], None] = '3b1b3b0a433c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_url', sa.String(), nullable=True),
    sa.Column('keyword_text', sa.String(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('marketing_product_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('cafe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['marketing_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cafe_id'], ['target_cafes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marketing_product_id'], ['marketing_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_posts_id'), 'marketing_posts', ['id'], unique=False)
    op.create_index(op.f('ix_marketing_posts_keyword_text'), 'marketing_posts', ['keyword_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketing_posts_keyword_text'), table_name='marketing_posts')
    op.drop_index(op.f('ix_marketing_posts_id'), table_name='marketing_posts')
    op.drop_table('marketing_posts')
    # ### end Alembic commands ###
