"""Add account_sequence to Comment

Revision ID: 2399a3c32f3a
Revises: a8e801699d41
Create Date: 2025-10-22 22:34:59.679040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2399a3c32f3a'
down_revision: Union[str, Sequence[str], None] = 'a8e801699d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('account_sequence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'account_sequence')
    # ### end Alembic commands ###
