"""Add account_sequence to Comment

Revision ID: 514961dbfbe1
Revises: e0fdf2fe5b6c
Create Date: 2025-10-27 17:51:51.740926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514961dbfbe1'
down_revision: Union[str, Sequence[str], None] = 'e0fdf2fe5b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
