"""Add category to MarketingAccount

Revision ID: 515c0c6d7f56
Revises: 029fd7e738cb
Create Date: 2025-10-22 16:44:41.778649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515c0c6d7f56'
down_revision: Union[str, Sequence[str], None] = '029fd7e738cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafe_memberships', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('cafe_memberships', 'is_suspended')
    op.add_column('marketing_accounts', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketing_accounts', 'category')
    op.add_column('cafe_memberships', sa.Column('is_suspended', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('cafe_memberships', 'status')
    # ### end Alembic commands ###
