"""Add customs BL columns to orders

Revision ID: 56c4f9015f59
Revises: 
Create Date: 2025-12-23 23:04:02.087135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c4f9015f59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_original_status'), table_name='order_status_mappings')
    op.drop_constraint(op.f('order_status_mappings_original_status_key'), 'order_status_mappings', type_='unique')
    op.create_index(op.f('ix_order_status_mappings_id'), 'order_status_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_order_status_mappings_original_status'), 'order_status_mappings', ['original_status'], unique=True)
    op.add_column('orders', sa.Column('master_bl', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('house_bl', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('customs_status', sa.String(length=50), nullable=True))
    op.alter_column('orders', 'order_number',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('idx_order_number'), table_name='orders')
    op.drop_constraint(op.f('orders_order_number_key'), 'orders', type_='unique')
    op.create_index(op.f('ix_orders_house_bl'), 'orders', ['house_bl'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_master_bl'), 'orders', ['master_bl'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_master_bl'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_house_bl'), table_name='orders')
    op.create_unique_constraint(op.f('orders_order_number_key'), 'orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_order_number'), 'orders', ['order_number'], unique=False)
    op.alter_column('orders', 'order_number',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('orders', 'customs_status')
    op.drop_column('orders', 'house_bl')
    op.drop_column('orders', 'master_bl')
    op.drop_index(op.f('ix_order_status_mappings_original_status'), table_name='order_status_mappings')
    op.drop_index(op.f('ix_order_status_mappings_id'), table_name='order_status_mappings')
    op.create_unique_constraint(op.f('order_status_mappings_original_status_key'), 'order_status_mappings', ['original_status'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_original_status'), 'order_status_mappings', ['original_status'], unique=False)
    # ### end Alembic commands ###
