"""Add Order table and can_manage_orders to User

Revision ID: 7ab2bd12b73a
Revises: 6f3aa405541f
Create Date: 2025-12-22 14:17:08.743795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab2bd12b73a'
down_revision: Union[str, Sequence[str], None] = '6f3aa405541f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('claim_date', sa.Date(), nullable=True),
    sa.Column('claim_reason', sa.Text(), nullable=True),
    sa.Column('sales_channel', sa.String(length=100), nullable=True),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('buyer_name', sa.String(length=100), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('courier_company', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('product_option', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('customs_number', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('customer_shipping_fee', sa.Float(), nullable=True),
    sa.Column('market_commission', sa.Float(), nullable=True),
    sa.Column('settlement_amount', sa.Float(), nullable=True),
    sa.Column('taobao_order_number', sa.String(length=100), nullable=True),
    sa.Column('taobao_yuan', sa.Float(), nullable=True),
    sa.Column('order_processing_date', sa.String(length=100), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('customs_prepayment', sa.Float(), nullable=True),
    sa.Column('freight_prepayment', sa.Float(), nullable=True),
    sa.Column('warehouse_fee', sa.String(length=100), nullable=True),
    sa.Column('profit_margin', sa.Float(), nullable=True),
    sa.Column('profit_margin_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
