"""Add account_sequence to Comment

Revision ID: 80ba94e410b2
Revises: 10cca33943b8
Create Date: 2025-10-24 00:23:04.988280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ba94e410b2'
down_revision: Union[str, Sequence[str], None] = '10cca33943b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_cafe_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('cafe_id', sa.Integer(), nullable=True),
    sa.Column('keyword_text', sa.String(), nullable=True),
    sa.Column('marketing_product_id', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['marketing_accounts.id'], ),
    sa.ForeignKeyConstraint(['cafe_id'], ['target_cafes.id'], ),
    sa.ForeignKeyConstraint(['marketing_product_id'], ['marketing_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'cafe_id', 'keyword_text', 'marketing_product_id')
    )
    op.create_index(op.f('ix_account_cafe_usage_id'), 'account_cafe_usage', ['id'], unique=False)
    op.create_index(op.f('ix_account_cafe_usage_keyword_text'), 'account_cafe_usage', ['keyword_text'], unique=False)
    op.create_table('posting_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketing_product_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('current_keyword_index', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marketing_product_id'], ['marketing_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posting_rounds_id'), 'posting_rounds', ['id'], unique=False)
    op.create_table('post_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('cafe_id', sa.Integer(), nullable=True),
    sa.Column('marketing_product_id', sa.Integer(), nullable=True),
    sa.Column('keyword_text', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('marketing_post_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['marketing_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cafe_id'], ['target_cafes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marketing_post_id'], ['marketing_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marketing_product_id'], ['marketing_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_schedules_id'), 'post_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_post_schedules_scheduled_date'), 'post_schedules', ['scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_schedules_scheduled_date'), table_name='post_schedules')
    op.drop_index(op.f('ix_post_schedules_id'), table_name='post_schedules')
    op.drop_table('post_schedules')
    op.drop_index(op.f('ix_posting_rounds_id'), table_name='posting_rounds')
    op.drop_table('posting_rounds')
    op.drop_index(op.f('ix_account_cafe_usage_keyword_text'), table_name='account_cafe_usage')
    op.drop_index(op.f('ix_account_cafe_usage_id'), table_name='account_cafe_usage')
    op.drop_table('account_cafe_usage')
    # ### end Alembic commands ###
