"""Add account_sequence to Comment

Revision ID: 8bc466d3076b
Revises: 1f9cfa12ee1b
Create Date: 2025-11-06 21:01:35.177081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc466d3076b'
down_revision: Union[str, Sequence[str], None] = '1f9cfa12ee1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
