"""Add cost fields for shipping and customs

Revision ID: a8e28f084cc8
Revises: d8ed480481af
Create Date: 2025-07-21 17:55:33.157666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e28f084cc8'
down_revision: Union[str, Sequence[str], None] = 'd8ed480481af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('customs_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'customs_cost')
    # ### end Alembic commands ###
