"""Add role columns to User model

Revision ID: af74d8de6386
Revises: 7306963bd627
Create Date: 2025-10-22 14:11:38.959797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af74d8de6386'
down_revision: Union[str, Sequence[str], None] = '7306963bd627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_manage_products', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_manage_marketing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_manage_marketing')
    op.drop_column('users', 'can_manage_products')
    # ### end Alembic commands ###
