"""Create CafeMembership association table

Revision ID: b08d09dd7948
Revises: e2dc6252b490
Create Date: 2025-10-22 15:58:09.346905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08d09dd7948'
down_revision: Union[str, Sequence[str], None] = 'e2dc6252b490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('cafe_id', sa.Integer(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('new_post_count', sa.Integer(), nullable=True),
    sa.Column('edited_post_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['marketing_accounts.id'], ),
    sa.ForeignKeyConstraint(['cafe_id'], ['target_cafes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe_memberships_id'), 'cafe_memberships', ['id'], unique=False)
    op.add_column('post_logs', sa.Column('membership_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('post_logs_account_id_fkey'), 'post_logs', type_='foreignkey')
    op.drop_constraint(op.f('post_logs_cafe_id_fkey'), 'post_logs', type_='foreignkey')
    op.create_foreign_key(None, 'post_logs', 'cafe_memberships', ['membership_id'], ['id'])
    op.drop_column('post_logs', 'account_id')
    op.drop_column('post_logs', 'cafe_id')
    op.drop_column('target_cafes', 'is_suspended')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_cafes', sa.Column('is_suspended', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('post_logs', sa.Column('cafe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post_logs', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post_logs', type_='foreignkey')
    op.create_foreign_key(op.f('post_logs_cafe_id_fkey'), 'post_logs', 'target_cafes', ['cafe_id'], ['id'])
    op.create_foreign_key(op.f('post_logs_account_id_fkey'), 'post_logs', 'marketing_accounts', ['account_id'], ['id'])
    op.drop_column('post_logs', 'membership_id')
    op.drop_index(op.f('ix_cafe_memberships_id'), table_name='cafe_memberships')
    op.drop_table('cafe_memberships')
    # ### end Alembic commands ###
