"""Add account_sequence to Comment

Revision ID: bfe61d7646b6
Revises: 2399a3c32f3a
Create Date: 2025-10-22 22:44:43.378205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe61d7646b6'
down_revision: Union[str, Sequence[str], None] = '2399a3c32f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'account_sequence',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'account_sequence',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
