"""Add account_sequence to Comment

Revision ID: c5964788fc41
Revises: 9d2ebf7cf6ab
Create Date: 2025-10-27 23:03:18.591335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5964788fc41'
down_revision: Union[str, Sequence[str], None] = '9d2ebf7cf6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
