"""Add account_sequence to Comment

Revision ID: c92fd6b86743
Revises: 8bc466d3076b
Create Date: 2025-11-06 21:11:10.073269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92fd6b86743'
down_revision: Union[str, Sequence[str], None] = '8bc466d3076b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('homepage_accounts_assigned_worker_id_fkey'), 'homepage_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'homepage_accounts', 'homepage_workers', ['assigned_worker_id'], ['id'])
    op.drop_constraint(op.f('homepage_keyword_progress_completed_post_id_fkey'), 'homepage_keyword_progress', type_='foreignkey')
    op.drop_constraint(op.f('homepage_keyword_progress_worker_id_fkey'), 'homepage_keyword_progress', type_='foreignkey')
    op.create_foreign_key(None, 'homepage_keyword_progress', 'homepage_posts', ['completed_post_id'], ['id'])
    op.create_foreign_key(None, 'homepage_keyword_progress', 'homepage_workers', ['worker_id'], ['id'])
    op.add_column('homepage_post_images', sa.Column('homepage_post_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('homepage_post_images_blog_post_id_fkey'), 'homepage_post_images', type_='foreignkey')
    op.create_foreign_key(None, 'homepage_post_images', 'homepage_posts', ['homepage_post_id'], ['id'])
    op.drop_column('homepage_post_images', 'blog_post_id')
    op.add_column('homepage_post_schedules', sa.Column('homepage_account_id', sa.Integer(), nullable=False))
    op.add_column('homepage_post_schedules', sa.Column('homepage_post_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('homepage_post_schedules_worker_id_fkey'), 'homepage_post_schedules', type_='foreignkey')
    op.drop_constraint(op.f('homepage_post_schedules_blog_post_id_fkey'), 'homepage_post_schedules', type_='foreignkey')
    op.drop_constraint(op.f('homepage_post_schedules_blog_account_id_fkey'), 'homepage_post_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'homepage_post_schedules', 'homepage_workers', ['worker_id'], ['id'])
    op.create_foreign_key(None, 'homepage_post_schedules', 'homepage_accounts', ['homepage_account_id'], ['id'])
    op.create_foreign_key(None, 'homepage_post_schedules', 'homepage_posts', ['homepage_post_id'], ['id'])
    op.drop_column('homepage_post_schedules', 'blog_account_id')
    op.drop_column('homepage_post_schedules', 'blog_post_id')
    op.add_column('homepage_posts', sa.Column('homepage_account_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('homepage_posts_blog_account_id_fkey'), 'homepage_posts', type_='foreignkey')
    op.drop_constraint(op.f('homepage_posts_worker_id_fkey'), 'homepage_posts', type_='foreignkey')
    op.create_foreign_key(None, 'homepage_posts', 'homepage_workers', ['worker_id'], ['id'])
    op.create_foreign_key(None, 'homepage_posts', 'homepage_accounts', ['homepage_account_id'], ['id'])
    op.drop_column('homepage_posts', 'blog_account_id')
    op.add_column('homepage_work_tasks', sa.Column('homepage_account_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('homepage_work_tasks_completed_post_id_fkey'), 'homepage_work_tasks', type_='foreignkey')
    op.drop_constraint(op.f('homepage_work_tasks_blog_account_id_fkey'), 'homepage_work_tasks', type_='foreignkey')
    op.drop_constraint(op.f('homepage_work_tasks_worker_id_fkey'), 'homepage_work_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'homepage_work_tasks', 'homepage_posts', ['completed_post_id'], ['id'])
    op.create_foreign_key(None, 'homepage_work_tasks', 'homepage_workers', ['worker_id'], ['id'])
    op.create_foreign_key(None, 'homepage_work_tasks', 'homepage_accounts', ['homepage_account_id'], ['id'])
    op.drop_column('homepage_work_tasks', 'blog_account_id')
    op.add_column('homepage_workers', sa.Column('is_homepage_manager', sa.Boolean(), nullable=True))
    op.drop_column('homepage_workers', 'is_blog_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homepage_workers', sa.Column('is_blog_manager', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('homepage_workers', 'is_homepage_manager')
    op.add_column('homepage_work_tasks', sa.Column('blog_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'homepage_work_tasks', type_='foreignkey')
    op.drop_constraint(None, 'homepage_work_tasks', type_='foreignkey')
    op.drop_constraint(None, 'homepage_work_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('homepage_work_tasks_worker_id_fkey'), 'homepage_work_tasks', 'blog_workers', ['worker_id'], ['id'])
    op.create_foreign_key(op.f('homepage_work_tasks_blog_account_id_fkey'), 'homepage_work_tasks', 'blog_accounts', ['blog_account_id'], ['id'])
    op.create_foreign_key(op.f('homepage_work_tasks_completed_post_id_fkey'), 'homepage_work_tasks', 'blog_posts', ['completed_post_id'], ['id'])
    op.drop_column('homepage_work_tasks', 'homepage_account_id')
    op.add_column('homepage_posts', sa.Column('blog_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'homepage_posts', type_='foreignkey')
    op.drop_constraint(None, 'homepage_posts', type_='foreignkey')
    op.create_foreign_key(op.f('homepage_posts_worker_id_fkey'), 'homepage_posts', 'blog_workers', ['worker_id'], ['id'])
    op.create_foreign_key(op.f('homepage_posts_blog_account_id_fkey'), 'homepage_posts', 'blog_accounts', ['blog_account_id'], ['id'])
    op.drop_column('homepage_posts', 'homepage_account_id')
    op.add_column('homepage_post_schedules', sa.Column('blog_post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('homepage_post_schedules', sa.Column('blog_account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'homepage_post_schedules', type_='foreignkey')
    op.drop_constraint(None, 'homepage_post_schedules', type_='foreignkey')
    op.drop_constraint(None, 'homepage_post_schedules', type_='foreignkey')
    op.create_foreign_key(op.f('homepage_post_schedules_blog_account_id_fkey'), 'homepage_post_schedules', 'blog_accounts', ['blog_account_id'], ['id'])
    op.create_foreign_key(op.f('homepage_post_schedules_blog_post_id_fkey'), 'homepage_post_schedules', 'blog_posts', ['blog_post_id'], ['id'])
    op.create_foreign_key(op.f('homepage_post_schedules_worker_id_fkey'), 'homepage_post_schedules', 'blog_workers', ['worker_id'], ['id'])
    op.drop_column('homepage_post_schedules', 'homepage_post_id')
    op.drop_column('homepage_post_schedules', 'homepage_account_id')
    op.add_column('homepage_post_images', sa.Column('blog_post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'homepage_post_images', type_='foreignkey')
    op.create_foreign_key(op.f('homepage_post_images_blog_post_id_fkey'), 'homepage_post_images', 'blog_posts', ['blog_post_id'], ['id'])
    op.drop_column('homepage_post_images', 'homepage_post_id')
    op.drop_constraint(None, 'homepage_keyword_progress', type_='foreignkey')
    op.drop_constraint(None, 'homepage_keyword_progress', type_='foreignkey')
    op.create_foreign_key(op.f('homepage_keyword_progress_worker_id_fkey'), 'homepage_keyword_progress', 'blog_workers', ['worker_id'], ['id'])
    op.create_foreign_key(op.f('homepage_keyword_progress_completed_post_id_fkey'), 'homepage_keyword_progress', 'blog_posts', ['completed_post_id'], ['id'])
    op.drop_constraint(None, 'homepage_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('homepage_accounts_assigned_worker_id_fkey'), 'homepage_accounts', 'blog_workers', ['assigned_worker_id'], ['id'])
    # ### end Alembic commands ###
