"""Add account_sequence to Comment

Revision ID: e0fdf2fe5b6c
Revises: 6c13c016ec1d
Create Date: 2025-10-27 16:34:43.699942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fdf2fe5b6c'
down_revision: Union[str, Sequence[str], None] = '6c13c016ec1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
