"""Add all marketing tables

Revision ID: e2dc6252b490
Revises: aee897970754
Create Date: 2025-10-22 15:36:33.749910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2dc6252b490'
down_revision: Union[str, Sequence[str], None] = 'aee897970754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('account_pw', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_accounts_account_id'), 'marketing_accounts', ['account_id'], unique=True)
    op.create_index(op.f('ix_marketing_accounts_id'), 'marketing_accounts', ['id'], unique=False)
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('ref_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_id'), 'references', ['id'], unique=False)
    op.create_table('target_cafes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_cafes_id'), 'target_cafes', ['id'], unique=False)
    op.create_index(op.f('ix_target_cafes_name'), 'target_cafes', ['name'], unique=False)
    op.create_index(op.f('ix_target_cafes_url'), 'target_cafes', ['url'], unique=True)
    op.create_table('marketing_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_products_id'), 'marketing_products', ['id'], unique=False)
    op.create_table('post_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('post_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('cafe_id', sa.Integer(), nullable=True),
    sa.Column('keyword_used', sa.String(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['marketing_accounts.id'], ),
    sa.ForeignKeyConstraint(['cafe_id'], ['target_cafes.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_logs_id'), 'post_logs', ['id'], unique=False)
    op.alter_column('products', 'product_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'product_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_post_logs_id'), table_name='post_logs')
    op.drop_table('post_logs')
    op.drop_index(op.f('ix_marketing_products_id'), table_name='marketing_products')
    op.drop_table('marketing_products')
    op.drop_index(op.f('ix_target_cafes_url'), table_name='target_cafes')
    op.drop_index(op.f('ix_target_cafes_name'), table_name='target_cafes')
    op.drop_index(op.f('ix_target_cafes_id'), table_name='target_cafes')
    op.drop_table('target_cafes')
    op.drop_index(op.f('ix_references_id'), table_name='references')
    op.drop_table('references')
    op.drop_index(op.f('ix_marketing_accounts_id'), table_name='marketing_accounts')
    op.drop_index(op.f('ix_marketing_accounts_account_id'), table_name='marketing_accounts')
    op.drop_table('marketing_accounts')
    # ### end Alembic commands ###
