"""Add account_sequence to Comment

Revision ID: f77357dcfb0b
Revises: 
Create Date: 2025-10-23 15:43:33.995913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77357dcfb0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_posts', sa.Column('post_title', sa.Text(), nullable=True))
    op.add_column('marketing_posts', sa.Column('post_body', sa.Text(), nullable=True))
    op.add_column('marketing_posts', sa.Column('post_comments', sa.Text(), nullable=True))
    op.add_column('marketing_posts', sa.Column('is_registration_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketing_posts', 'is_registration_complete')
    op.drop_column('marketing_posts', 'post_comments')
    op.drop_column('marketing_posts', 'post_body')
    op.drop_column('marketing_posts', 'post_title')
    # ### end Alembic commands ###
