"""Add ON DELETE CASCADE to foreign keys

Revision ID: f933d53e8dbc
Revises: 34ec5d53163e
Create Date: 2025-10-22 17:29:44.511616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f933d53e8dbc'
down_revision: Union[str, Sequence[str], None] = '34ec5d53163e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cafe_memberships_cafe_id_fkey'), 'cafe_memberships', type_='foreignkey')
    op.drop_constraint(op.f('cafe_memberships_account_id_fkey'), 'cafe_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'cafe_memberships', 'marketing_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cafe_memberships', 'target_cafes', ['cafe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_logs_membership_id_fkey'), 'post_logs', type_='foreignkey')
    op.create_foreign_key(None, 'post_logs', 'cafe_memberships', ['membership_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_logs', type_='foreignkey')
    op.create_foreign_key(op.f('post_logs_membership_id_fkey'), 'post_logs', 'cafe_memberships', ['membership_id'], ['id'])
    op.drop_constraint(None, 'cafe_memberships', type_='foreignkey')
    op.drop_constraint(None, 'cafe_memberships', type_='foreignkey')
    op.create_foreign_key(op.f('cafe_memberships_account_id_fkey'), 'cafe_memberships', 'marketing_accounts', ['account_id'], ['id'])
    op.create_foreign_key(op.f('cafe_memberships_cafe_id_fkey'), 'cafe_memberships', 'target_cafes', ['cafe_id'], ['id'])
    # ### end Alembic commands ###
