"""Add account_sequence to Comment

Revision ID: d393eed5ad6e
Revises: 
Create Date: 2025-10-24 11:42:43.995300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd393eed5ad6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('marketing_posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('marketing_posts', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('marketing_posts', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('marketing_posts', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('naver_link', sa.String(length=2083), nullable=True))
    op.add_column('products', sa.Column('naver_options', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'naver_options')
    op.drop_column('products', 'naver_link')
    op.drop_column('marketing_posts', 'comment_count')
    op.drop_column('marketing_posts', 'like_count')
    op.drop_column('marketing_posts', 'view_count')
    op.drop_column('marketing_posts', 'updated_at')
    op.drop_column('marketing_posts', 'created_at')
    # ### end Alembic commands ###
